// Generates heroicons icon libraries from lib/heroicons_list.dart.
//
// Run from the package root:
//   dart run tool/generate_heroicons.dart
//
// Output:
//   lib/heroicons_flutter.dart — public API (.bookOpen, .named(), .fromString)

import 'dart:io';

final _iconPattern = RegExp(
  r'Heroicon\(name:\s*"([^"]+)",\s*code:\s*(0x[0-9a-fA-F]+)\)',
);

class _Variant {
  const _Variant({
    required this.className,
    required this.fontFamilyConst,
    required this.mapName,
    required this.style,
  });

  final String className;
  final String fontFamilyConst;
  final String mapName;
  final String style;
}

const _variants = [
  _Variant(
    className: 'HeroiconsSolid',
    fontFamilyConst: '_solidFontFamily',
    mapName: '_solidIconsByName',
    style: 'solid',
  ),
  _Variant(
    className: 'HeroiconsOutline',
    fontFamilyConst: '_outlineFontFamily',
    mapName: '_outlineIconsByName',
    style: 'outline',
  ),
  _Variant(
    className: 'HeroiconsMini',
    fontFamilyConst: '_miniFontFamily',
    mapName: '_miniIconsByName',
    style: 'mini',
  ),
  _Variant(
    className: 'HeroiconsMicro',
    fontFamilyConst: '_microFontFamily',
    mapName: '_microIconsByName',
    style: 'micro',
  ),
];

class _IconEntry {
  const _IconEntry({required this.name, required this.code});

  final String name;
  final String code;
}

void main() {
  final packageRoot = Directory.current;
  final listFile = File('${packageRoot.path}/lib/heroicons_list.dart');
  final libDir = Directory('${packageRoot.path}/lib');

  if (!listFile.existsSync()) {
    stderr.writeln('Could not find ${listFile.path}');
    stderr.writeln('Run this script from the package root.');
    exit(1);
  }

  final icons = _parseIcons(listFile.readAsStringSync());
  if (icons.isEmpty) {
    stderr.writeln('No icons found in ${listFile.path}');
    exit(1);
  }

  _write('${libDir.path}/heroicons_flutter.dart', _generate(icons));

  for (final path in [
    '${libDir.path}/heroicons_flutter_static.dart',
    '${libDir.path}/heroicons_flutter_dynamic.dart',
  ]) {
    final file = File(path);
    if (file.existsSync()) {
      file.deleteSync();
      stdout.writeln('  removed $path');
    }
  }

  final srcDir = Directory('${libDir.path}/src');
  if (srcDir.existsSync()) {
    srcDir.deleteSync(recursive: true);
    stdout.writeln('  removed ${srcDir.path}');
  }

  stdout.writeln(
    'Generated heroicons_flutter.dart with ${icons.length} icons '
    'x ${_variants.length} variants.',
  );
}

void _write(String path, String contents) {
  File(path).writeAsStringSync(contents);
  stdout.writeln('  wrote $path');
}

List<_IconEntry> _parseIcons(String source) {
  return _iconPattern
      .allMatches(source)
      .map(
        (match) => _IconEntry(
          name: match.group(1)!,
          code: match.group(2)!.toLowerCase(),
        ),
      )
      .toList();
}

String _generatedHeader(String description) {
  return '''
// GENERATED CODE - DO NOT EDIT BY HAND
//
// Generated by: dart run tool/generate_heroicons.dart
// Source: lib/heroicons_list.dart
//
// $description
''';
}

String _fontConstants() {
  return '''
const _fontPackage = 'heroicons_flutter';
const _solidFontFamily = 'Heroicons Solid';
const _outlineFontFamily = 'Heroicons Outline';
const _miniFontFamily = 'Heroicons Mini';
const _microFontFamily = 'Heroicons Micro';
''';
}

String _generate(List<_IconEntry> icons) {
  final buffer = StringBuffer()
    ..write(_generatedHeader('Public package API.'))
    ..writeln()
    ..writeln('library heroicons_flutter;')
    ..writeln()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..write(_fontConstants())
    ..writeln()
    ..write(_helpers);

  for (final variant in _variants) {
    buffer.writeln('class ${variant.className} {');
    for (final icon in icons) {
      buffer.writeln(
        '  static const ${icon.name} = '
        'IconData(${icon.code}, '
        'fontFamily: ${variant.fontFamilyConst}, '
        'fontPackage: _fontPackage);',
      );
    }
    buffer
      ..writeln()
      ..writeln('  static const ${variant.mapName} = <String, IconData>{');
    for (final icon in icons) {
      buffer.writeln("    '${icon.name}': ${icon.name},");
    }
    buffer
      ..writeln('  };')
      ..writeln()
      ..writeln('  static IconData named(String name) {')
      ..writeln(
        "    return _iconFromName(name, ${variant.mapName}, '${variant.style}');",
      )
      ..writeln('  }')
      ..writeln()
      ..writeln("  @Deprecated('Use named() instead')")
      ..writeln('  static IconData fromString(String name) => named(name);')
      ..writeln('}')
      ..writeln();
  }

  return buffer.toString();
}

const _helpers = '''
IconData _iconFromName(
  String name,
  Map<String, IconData> icons,
  String style,
) {
  final camelCase = _toCamelCase(name);
  final icon = icons[camelCase];
  if (icon != null) {
    return icon;
  }

  for (final entry in icons.entries) {
    if (entry.key.toLowerCase() == camelCase.toLowerCase()) {
      return entry.value;
    }
  }

  throw 'No such \$style heroicon with the given name: \$name';
}

String _toCamelCase(String input) {
  final splitted = input.split(RegExp(r"[\\s\\-\\_\\.]"));

  String result =
      splitted[0].substring(0, 1).toLowerCase() + splitted[0].substring(1);

  for (var i = 1; i < splitted.length; i++) {
    result += splitted[i].substring(0, 1).toUpperCase() +
        splitted[i].substring(1).toLowerCase();
  }

  return result;
}

''';
